name: delta_auth
description: 三角洲授权 - 免root授权登录工具
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
